### ISSUE TITLE
Add transparency to shapes in the geometry and mesh editors

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#217]
Neither the geometry editor nor the mesh editor allow me to make shapes partially or fully transparent. This is often necessary for working with complex designs so we should add it.

**Comment by SmithRWORNL** [comment]
Opacity support for JavaFX is unfortunately lacking. Setting an object to full opacity or full transparency works fine, but partial transparency has a problem.

![screen shot 2016-06-01 at 1 24 25 pm](https://cloud.githubusercontent.com/assets/12715269/15719137/89513322-27fc-11e6-8477-43ff163fbddc.png)

As you can see in the screenshot, JavaFX has no concept of transparent objects' depths, instead ordering them based on when they were added to the scene. This leads to strange graphical errors, like the one seen above. 

Hypothetically, this could be resolved by finding the correct ordering from nearest to farthest from the camera ourselves, and reordering everything whenever the camera is moved or the scene is edited, but transparency ordering seems to be a very difficult problem on its own. JavaFX 9 may have a partial solution according to the [official JavaFX bug tracker](https://bugs.openjdk.java.net/browse/JDK-8090548). Until JavaFX offers this functionality, I would suggest using wireframe objects instead of partially transparent ones. Would this be acceptable?

**Comment by jayjaybillings** [comment]
Yes, wireframe objects instead would be a good workaround for partial transparency. Let's provide that and full transparency.

**Comment by SmithRWORNL** [comment]
As of commit e804fdb71f5ebe2ee9b4bf0695756afbe3fb67e5 to the next branch of EAVP, a selected shape can now be set to wireframe or transparent mode via the use of a combo box in the Transformation View.

In the Mesh Editor, a polygon, edge, or vertex can be set to wireframe or transparent by selecting it in the Mesh Element View and choosing the desired option from the opacity combo box in its Properties tab.
