### ISSUE TITLE
Calling loadInput from setupForm in Model template

### ISSUE THREAD

**Issue by amccaskey** [eclipse/ice#233]
https://github.com/eclipse/ice/blob/next/org.eclipse.ice.projectgeneration/templates_3.4/ICEItem/src/%24className%24Model.java#L92

I don't think this is what we want as our setupForm template for the to-be-created Model Item. 

loadItem is for loading Items from existing input files and I don't think we should tie it to the setupForm method. We had fixed this before the last tutorial, but it seems to have creeped back in.

**Comment by jayjaybillings** [comment]
It will probably break if you tie them together. I know I've had that happen a few times. I agree, we don't want it this way.


Jay Jay Billings
Oak Ridge National Laboratory
Twitter Handle: @jayjaybillings
________________________________

**Comment by amccaskey** [comment]
addressed in d6c1adea01c9f7c7e9eef935ae707de3d782cb96

**Comment by arbennett** [comment]
There is a problem with the fix where if you just create the item from scratch via the `+` button in the ICE perspective nothing will come up since the form has no components.  To make it work with the current setup we need to have some other method being called that loads up the default dataset then.  

The `loadInput(null)` call was to load the default dataset provided when creating the item via the wizard.  How would we go about checking if the item was created via the `+` vs importing a file and using that to call `loadInput`?

I don't think I've ever had it break under that scheme, but I'm certainly not an expert on all the architecture underlying items.  Could someone explain why this is a bad idea?

**Comment by jayjaybillings** [comment]
I reviewed what you wrote @arbennett. In principle, it is keeping with the API documentation that loadInput is for loading from files, but 95% of it is about loading defaults. That code is better placed in an operation called loadDefaults, which might be something that we should consider offering on the base class. Furthermore, such code will essentially drop new developers off the deep end of the Eclipse APIs, which we don't want. 

I like the code and the idea, so please open a ticket for us to investigate adding a loadDefaults operation to the base class.

Now, as to how this might break. There is a major flaw in the design of the Item base class which I have yet to fix, which is that setupForm() is called as part of the constructor. The proper way to do this is to make call that function after the constructor and let the builder interface encapsulate the logic. That is the whole purpose of having a builder backed for the Item to begin with, btw. The problem with setupForm() being part of the constructor means that the loadInput operation could be, but might not always be, called before the form is initialized properly or even before the project is properly configured. If you look at the documentation of loadInput, it explicitly warns against this possibility because I encountered it with the ProteusModel and Nek5000Model in the past.

Does that make sense?

**Comment by arbennett** [comment]
Thanks @jayjaybillings that makes sense.  I've created #236 to discuss how we should handle this in the semi-near future.
