### ISSUE TITLE
Reference list of ICE content

### ISSUE THREAD

**Issue by jarrah42** [eclipse/ice#240]
We should really have a reference list of the content that is included in the ICE product. It is very easy to end up with a 900MB executable as we have seen, so it is important to have a good reason for each feature being included.

**Comment by jayjaybillings** [comment]
Well, the reason is simple. We put things in ICE based on the following question: "Do Jay and @amccaskey, as prime examples of scientific software engineers, regularly use the capability inside Eclipse?" If the answer is yes, then it goes into ICE. 

You are right, though: We definitely need to start listing what we cram in, which will help with the evaluation of what should and should not go into the dev menu as part of my discussion in #238.
