### ISSUE TITLE
404 Not Found on eclipseice.ornl.gov

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#255]
The Eclipse ICE downloads page at ORNL is busted. The top few directories work fine, but the P2 site returns errors on its subfolders:
http://eclipseice.ornl.gov/downloads/ice/unstable-nightly/20160812/p2/features/

**Comment by amccaskey** [comment]
The script is working - this is happening because there are no binaries at http://download.eclipse.org/ice/builds/next/ice-*-2.1.8.zip

Looking at the build and validating the archiving of products I get this: 

<img width="1323" alt="screen shot 2016-08-15 at 2 40 33 pm" src="https://cloud.githubusercontent.com/assets/827531/17675097/3071a14e-62f6-11e6-8712-845676ab53d0.png">

Maybe because we haven't had a successful build in awhile:

<img width="300" alt="screen shot 2016-08-15 at 2 41 37 pm" src="https://cloud.githubusercontent.com/assets/827531/17675121/4bf9d792-62f6-11e6-91ee-b0705368af1a.png">

**Comment by amccaskey** [comment]
I see - our products are now named 

ice.runtime.product-*.zip and ice.sdk.product-*.zip
