### ISSUE TITLE
Mac OS X and Environment Variables

### ISSUE THREAD

**Issue by amccaskey** [eclipse/ice#288]
Came across this problem with Sam the other day: 

It appears that ICE (and any Java app) on Mac OS X does not by default read in the current users shell environment variables. Sam tried to invoke the Moose and Libmesh build targets in ICE, and it failed because variables like PETSC_DIR were not set. This bug is Eclipse wide it appears [#490816](https://bugs.eclipse.org/bugs/show_bug.cgi?id=490816). That bug references other links discussing this problem 

http://stackoverflow.com/questions/829749/launch-mac-eclipse-with-environment-variables-set/36282543

http://apple.stackexchange.com/questions/51677/how-to-set-path-for-finder-launched-applications

http://stackoverflow.com/questions/30118905/read-path-variable-using-java-in-eclipse-on-mac-os-x-differs-from-shell/36282645#36282645

A common way to fix this is to modify the ICE Mac App package to execute a shell script instead of the internal executable (ICE.sh instead of ICE in ICE.app/Contents/MacOS folder), where the shell script sources the users bash_profile. Not sure how to get this working through the product build.

**Comment by jayjaybillings** [comment]
I don't think we can fix this. Even if we could, this is clearly a better task for @amccaskey than @SmithRWORNL, so I have reassigned it. 

My concern here is that we probably can't modify the launcher script. There are several problems here related to signing, packaging and building. Have you seen any good examples from Eclipse bugs on how to fix this?

**Comment by SmithRWORNL** [comment]
@jayjaybillings I've found a Maven plugin https://github.com/buchen/fix-info-plist-maven-plugin that can edit the info.plist to point to a script we package into the executable's content and though I hadn't started looking into signing yet I don't see a simple change in where the executable is being pointed as an insurmountable problem there, so it doesn't seem impossible in principle,

**Comment by jayjaybillings** [comment]
I know it isn't impossible in principle, but what I'm saying is that it may not be impractical. Are there any bugs filed with Eclipse on this?

If the info.plist can be edited before signing, then there won't be a problem with the actual signing step. just make sure the script has its executable bit set before packaging and signing.

**Comment by ds-ga-1007** [comment]
Yes: https://bugs.eclipse.org/bugs/show_bug.cgi?id=490816

This has been a problem with the Mac version of Eclipse for a long time, since Apple has changed the way environment variables are handled by the Finder a number of times. It's also a problem in Linux, but not to the same extent. I don't think Java developers care very much since they don't tend to run external programs, hence it is not a priority for Platform. It is more likely to affect packages that run things externally, like CDT, PTP, etc. It should really be fixed in the launcher though.

Users expect the environment to be the same as their login shell, so I think the fix should really be to start a login shell and find out what environment variables have been set. These could then be copied to the Eclipse environment. I could look at what needed to be done in the launcher and see if we could get the change accepted.

**Comment by jayjaybillings** [comment]
Agreed - getting this in the launcher is the ideal solution. If you would be interested in pushing forward on that, I think it would be great.

As for ICE, @amccaskey and @SmithRWORNL, please do what you can and keep this ticket updated. If the plist solution works, then that is a "good enough for now" solution.
