### ISSUE TITLE
Make the Developer menu more flexible

### ISSUE THREAD

**Issue by jarrah42** [eclipse/ice#309]
Currently the Developer menu provides a fairly rigid structure through the use of the org.eclipse.ice.developer.code extension point. The extension point assumes that all code elements will be related to a repository, and will fit into one of the predefined categories. The menu is also generated programmatically, so it is not possible to add menus through the normal org.eclipse.ui.menu extension point. I ran into this problem, because I want to add a menu to one of the categories this way.

I would like to suggest that we change the Developer menu to use the normal menu/command/handler mechanism in order to allow more flexible use of the menu and sub-menus. It should still be possible to use an extension point like org.eclipse.ice.developer.code for specific types of handlers if so desired, or simply provide an abstract handler implementation that does the same thing.

**Comment by jarrah42** [comment]
#259

**Comment by jayjaybillings** [comment]
@amccaskey What do you think? If we are going to move on this then we need to do it soon because it is blocking #259.

@waynebeaton caught #259 in an IP log review, so we need to get it fixed sooner rather than later.

Overall, I agree with Greg's assessment. It isn't clear to me in the current scheme how I would add a bunch of custom Docker-related stuff, things that pull from SVN, or things that download directly from a website.

**Comment by amccaskey** [comment]
@jarrah42 I am totally open to improving on this mechanism. Feel free to take a crack at it. 

I will say though that the extension points don't have to be associated with a repository (see BuildICEHandler, LaunchNewICEHandler). You can associate each developer extension with an AbstractHandler implementation - that's pretty extensible to adding new actions if you ask me. If someone points me to an example of how to programmatically download and install the p2 repo for EASE Jython I could spin up a prototype in like 20 minutes. 

As for the docker stuff, I feel like we would just have to add a new category - Development Environments or something like that, then we would just create new extensions via XML that point to a custom DockerAbstractHandler for example.

**Comment by jayjaybillings** [comment]
Also, I don't think we need to rewrite the handlers. Basically all we need to do is rewrite the code that programmatically declares the menu, right?

**Comment by jarrah42** [comment]
Right, this is using the existing handlers, just redoing the menus via extensions. See greg/devmenu branch for prototype.

**Comment by jayjaybillings** [comment]
How's this doing? I got an email from the IP team about #259 yesterday, which depends on this one.

**Comment by jarrah42** [comment]
I thought someone (Alex?) was going to review the changes I put in greg/devmenu

**Comment by jayjaybillings** [comment]
@amccaskey will you take a look at it please?

**Comment by amccaskey** [comment]
I believe I responded back on the slack channel back when we were talking about this that it looked good to me.

Any way it looks good to me.

**Comment by amccaskey** [comment]
Not slack... mattermost.

**Comment by jayjaybillings** [comment]
Yes, you did. You said you would push it to next if it was OK with me and I said it is OK. Will you push it please?

**Comment by amccaskey** [comment]
yea sure thing.

**Comment by SmithRWORNL** [comment]
Tested this out by merging greg/devmenu with next and building it.

Doing Developer -> ICE -> Clone gets to 100% then stops and cannot be canceled. The repo is cloned into the workspace, but the projects do not get imported into the workspace automatically.

The repo is also not normally loaded into the git perspective. But if the chosen workspace is nested inside another workspace that has an ICE git repo then the outer workspace's git repo will be imported instead. (ie I built ICE, ran clone, and it imported the repo with the branch merged into next, rather than the new repo it just downloaded).

**Comment by jarrah42** [comment]
Do you see this behavior in the next branch or only this branch?

**Comment by amccaskey** [comment]
Just tried it out on next - ICE Clone and works as expected. 

Turns out the problem was that the cloneAndFix command id was pointing to FixMavenLifecycleCloneHandler and not ICECloneHandler. Changing it to ICECloneHandler seems to fix the problem.

**Comment by SmithRWORNL** [comment]
After further investigation, this issue seems to be localized entirely to my Windows computer. It is affecting all ICE instances I run, even old versions of ICE which I had previously used the developer clone action in successfully, but not affecting anything, even next with greg/devmenu merged in, on my Mac laptop.

The branch itself seems fine, I'm going to go ahead and commit the merged branch.

**Comment by jayjaybillings** [comment]
So is this issue closed?

**Comment by jarrah42** [comment]
Yes.
