### ISSUE TITLE
Need to clean out ICE HIPP instance

### ISSUE THREAD

**Issue by jarrah42** [eclipse/ice#337]
As requested by webmaster: https://dev.eclipse.org/mhonarc/lists/cross-project-issues-dev/msg14135.html

**Comment by jayjaybillings** [comment]
?Greg, will you follow up on this please? I just looked at it and I'm not sure why we hitting that limit because we only have about 55 builds total. I think it must be log information.


Jay


Jay Jay Billings
Oak Ridge National Laboratory
Twitter Handle: @jayjaybillings
________________________________

**Comment by jarrah42** [comment]
Build + artifacts are 5GB for each job + 16GB for the workspace. There's 41 builds for next, so I think the numbers are about right. They recommend only keeping 5-10 builds, so I'll change it to 10.

**Comment by jayjaybillings** [comment]
Wow. That's amazing...


I noticed that next is turned off. Will you turn it on please?

?


Jay Jay Billings
Oak Ridge National Laboratory
Twitter Handle: @jayjaybillings
________________________________

**Comment by jarrah42** [comment]
It's not turned off that I can see. The last build was aborted, which is why the icon is grey.

**Comment by jayjaybillings** [comment]
Ah. We probably haven't pushed to that branch in awhile then.


Jay


Jay Jay Billings
Oak Ridge National Laboratory
Twitter Handle: @jayjaybillings
________________________________

**Comment by jarrah42** [comment]
Completed
