### ISSUE TITLE
Can't open Vaadin Designer on Fedora using ICE

### ISSUE THREAD

**Issue by anarak** [eclipse/ice#350]
When I tried to open Vaadin Designer with ICE and GTK2 enabled, I got the following error attached. I had no problems except some glitches in Properties window in the Designer with Eclipse Oxygen that had GTK3 set.

Vaadin recommends launching Eclipse with GTK2 and Cairo enabled as explained [here](https://vaadin.com/wiki/-/wiki/Main/Vaadin+Designer+FAQ). Fedora had webkitgtk3 pre-installed and Eclipse with GTK3 worked just fine. In order to switch to GTK2 to run the designer properly, a compatible version of webkitgtk needs to be installed first I believe.

Installing webkitgtk and enabling GTK2/Cairo allowed running Vaadin Designer in Eclipse and also ICE normally without the glitches related to Properties view in the Designer.  There is a webkit2gtk which is newer than webkitgtk <- putting it here for the record.

![screenshot from 2017-02-21 08-56-53](https://cloud.githubusercontent.com/assets/25353166/23222048/b5dcbca8-f8f4-11e6-9b54-dda09db79ae3.png)

**Comment by jayjaybillings** [comment]
I can't reproduce this. It works fine on my version of Fedora, although I have multiple versions of webkitgtk installed.

ICE sets the version of GTK to GTK 2 by default using the "--launcher.GTK_version 2" in its INI file so that it will run on Linux without GTK 3 problems. All of these problems are outside of ICE and the best we can do is write a note for users on workarounds.
