### ISSUE TITLE
Feature versions in 2.2.1 are still set to 2.2.0

### ISSUE THREAD

**Issue by jarrah42** [eclipse/ice#353]
As the title says, the feature versions need to be incremented to match the release version.

**Comment by jayjaybillings** [comment]
Yes, all the 2.2.1 version numbers need to be updated. Poms, manifests, plugins, features, everything. I wanted to get the build working and dumping into /2.2.1 first so I didn't change them over the weekend. I wanted to reduce the possibility that overlapping bugs existed because I changed too many things at once.

**Comment by jayjaybillings** [comment]
Done in the 2.2.1 branch.
