### ISSUE TITLE
Item and Datastructures bundle depend on Viz bundles

### ISSUE THREAD

**Issue by amccaskey** [eclipse/ice#69]
I just noticed that org.eclipse.ice.item depends indirectly on org.eclipse.ice.viz.* through its dependence on org.eclipse.ice.datastructures. Datastructures depends on these for ICEGeometry and ICEShape. 

I'm don't think its a good idea for Item/Datastructures to depend on Viz bundles, especially when the Viz bundles will be moved to another project soon.

**Comment by jayjaybillings** [comment]
Alex,

I don't have a problem with it. I think it is fine because the viz bundles will very soon be third party dependencies like any other piece of Eclipse.

Jay

From my phone.
________________________________
From: Alex McCaskey
Sent: Thursday, December 17, 2015 4:39 PM
To: eclipse/ice
Subject: [ice] Item and Datastructures bundle depend on Viz bundles (#69)



I just noticed that org.eclipse.ice.item depends indirectly on org.eclipse.ice.viz.* through its dependence on org.eclipse.ice.datastructures. Datastructures depends on these for ICEGeometry and ICEShape.

I'm don't think its a good idea for Item/Datastructures to depend on Viz bundles, especially when the Viz bundles will be moved to another project soon.

-

**Comment by SmithRWORNL** [comment]
@amccaskey 

At some point, one of the two halves has to have some way to address the other in order for them to work together. The only alternative I see is that the viz.* bundles be made to depend on the rest of ICE, which is even worse.

**Comment by jayjaybillings** [comment]
This is basic layered architecture stuff. The viz bundles will very, very soon be third party dependencies that exist at the bottom of the dependency stack, so any "higher" bundle can use them. A problem would only exist if they called up the dependency stack. 

So, it isn't bad. It is a completely normal and valid way of handling a dependency.

It will be even clearer in a few months when the new Eclipse Science Data Structures project gets going. We will move all of our data structures from ICE and EAVP into that project as well as IDataSet from DAWN. Then nearly everything in Science will use that data structures bundle.

I'm going to close this ticket since this isn't a bug.

**Comment by amccaskey** [comment]
Thanks for looking at this. Just wanted to make sure this wasn't a problem moving forward.
